server:
    port: 4002
    error: 
        include-message: always


spring:
    ## db
    datasource:
        url: jdbc:mysql://localhost:3306/vorspiel
        # url: jdbc:h2:mem:vorspiel.db
        username: root
        password:
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        # database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create-drop
        defer-datasource-initialization: true
        open-in-view: false
        # console: 
        #     enabled: true
        #     path: /h2

    ## mail (maildev access inbox on localhost:1080)
    mail:
        host: localhost
        port: 1025
        sender: 
            name: DocumentBuilder Team
            email: documentBuilder.mailing@outlook.de

    config:
        import: optional:file:.env[.properties] # include .env file